version: 2
updates:

  - package-ecosystem: "github-actions"
    commit-message:
      include: "scope"
      prefix: "Actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"  # Group all Actions updates into a single larger pull request
    labels:
      - "enhancement"
    schedule:
      interval: "weekly"
